repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2
    hooks:
        # Linter first.
    -   id: ruff
        args: [ --fix ]
        # Format later.
    -   id: ruff-format
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files