# Generated by Django 5.1.1 on 2024-09-04 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(verbose_name="session date")),
                (
                    "members",
                    models.CharField(max_length=200, verbose_name="session members"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.PositiveIntegerField(verbose_name="alert timestamp"),
                ),
                (
                    "count",
                    models.PositiveSmallIntegerField(
                        verbose_name="number of free slots"
                    ),
                ),
                (
                    "members",
                    models.CharField(max_length=200, verbose_name="members dropped"),
                ),
                (
                    "calendar_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.calendar"
                    ),
                ),
            ],
        ),
    ]
