# Generated by Django 5.1.1 on 2024-09-05 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calendar',
            new_name='Session',
        ),
    ]
