# Generated by Django 5.1.1 on 2024-09-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_calendar_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.PositiveIntegerField(verbose_name='alert UNIX timestamp'),
        ),
        migrations.AlterField(
            model_name='session',
            name='datetime',
            field=models.CharField(max_length=13, verbose_name='session date'),
        ),
    ]
