# Generated by Django 5.1.1 on 2024-09-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_session_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='datetime',
            field=models.CharField(max_length=13, verbose_name='session date'),
        ),
    ]
