# Generated by Django 5.1.1 on 2024-09-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_session_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='calendar_entry',
            new_name='session',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='members',
        ),
    ]
